/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controladores.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jeany
 */
public class P1 extends javax.swing.JDialog {

    /**
     * Creates new form P1
     *
     * @param parent
     * @param modal
     */
    public P1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        insertJTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCamadaEntrada = new javax.swing.JLabel();
        jLabelCamadaOculta = new javax.swing.JLabel();
        jLabelCamadaSaida = new javax.swing.JLabel();
        jTextFieldOculta = new javax.swing.JTextField();
        jTextFieldSaida = new javax.swing.JTextField();
        jTextFieldEntrada = new javax.swing.JTextField();
        jButtonProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Treinar Rede");

        jLabelCamadaEntrada.setText("Camada Entrada");

        jLabelCamadaOculta.setText("CamadaOculta");

        jLabelCamadaSaida.setText("Camada Saída");

        jTextFieldSaida.setEditable(false);

        jTextFieldEntrada.setEditable(false);

        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCamadaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCamadaOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCamadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProximo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamadaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamadaOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamadaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonProximo)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTextFieldOculta.getAccessibleContext().setAccessibleName("");
        jTextFieldSaida.getAccessibleContext().setAccessibleName("");
        jTextFieldEntrada.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        try{
            ControladorRedeNeural.alocaCamadaEntrada();
            ControladorRedeNeural.alocaCamadaOculta(Integer.parseInt(jTextFieldOculta.getText()));
            ControladorRedeNeural.alocaCamadaSaida();

            ControladorRedeNeural.conectaRedeNeural();
            ControladorRedeNeural.inserePesosAleatórios();
            
            new P2(Main.Main.principal, true).setVisible(true);

            this.dispose();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Valor incorreto");
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed
    
    private void insertJTextField() {
        jTextFieldEntrada.setText(Integer.toString(ControladorArquivo.quantEntrada()));
        jTextFieldOculta.setText(Integer.toString((int) Math.round(Math.sqrt(ControladorArquivo.quantEntrada() * ControladorArquivo.quantClasses()))));
        jTextFieldSaida.setText(Integer.toString(ControladorArquivo.quantClasses()));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JLabel jLabelCamadaEntrada;
    private javax.swing.JLabel jLabelCamadaOculta;
    private javax.swing.JLabel jLabelCamadaSaida;
    private javax.swing.JTextField jTextFieldEntrada;
    private javax.swing.JTextField jTextFieldOculta;
    private javax.swing.JTextField jTextFieldSaida;
    // End of variables declaration//GEN-END:variables
}
